org.gradle.jvmargs=-Xmx4G
org.gradle.java.home=C:/Program Files/Eclipse Adoptium/jdk-25.0.1.8-hotspot
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=26.1
loader_version=0.18.6
loom_version=1.16-SNAPSHOT
fabric_api_version=0.145.1+26.1

# Mod Properties
mod_version=1.4
maven_group=net.cozystudios.tokimistoolshed
